SELECT
    ticker,
    snapshot_timestamp,
    market_cap,
    trailing_pe,
    forward_pe,
    peg_ratio,
    price_to_book,
    price_to_sales,
    enterprise_value,
    enterprise_to_revenue,
    enterprise_to_ebitda,
    profit_margins,
    gross_margins,
    operating_margins,
    ebitda_margins,
    return_on_assets,
    return_on_equity,
    revenue_growth,
    earnings_growth,
    earnings_quarterly_growth,
    trailing_eps,
    forward_eps,
    revenue_per_share,
    book_value,
    total_cash_per_share,
    dividend_rate,
    dividend_yield,
    payout_ratio,
    five_year_avg_dividend_yield,
    toDate(dividend_date) as dividend_date,
    toDate(ex_dividend_date) as ex_dividend_date,
    total_cash,
    total_debt,
    debt_to_equity,
    current_ratio,
    quick_ratio,
    free_cashflow,
    operating_cashflow,
    total_revenue,
    gross_profits,
    ebitda,
    net_income,
    fifty_two_week_low,
    fifty_two_week_high,
    fifty_two_week_change,
    fifty_day_average,
    two_hundred_day_average,
    ingestion_datetime
FROM
    s3(
        '{{ env_var("S3_HOST") }}/yahoo-finance/financial/*.parquet',
        '{{ env_var("S3_ACCESS_KEY_ID") }}',
        '{{ env_var("S3_SECRET_ACCESS_KEY") }}',
        'Parquet'
    )
